# Generated by Django 3.0.1 on 2020-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
